export const locationData = {
  "AP": ["Andhra Pradesh", ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool"]],
  "AR": ["Arunachal Pradesh", ["Itanagar", "Tawang", "Naharlagun", "Ziro", "Pasighat"]],
  "AS": ["Assam", ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon"]],
  "BR": ["Bihar", ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga"]],
  "CG": ["Chhattisgarh", ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg"]],
  "GA": ["Goa", ["Panaji", "Margao", "Vasco-da-Gama", "Mapusa", "Ponda"]],
  "GJ": ["Gujarat", ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar"]],
  "HR": ["Haryana", ["Chandigarh", "Gurugram", "Faridabad", "Panipat", "Ambala"]],
  "HP": ["Himachal Pradesh", ["Shimla", "Manali", "Dharamshala", "Kullu", "Solan"]],
  "JH": ["Jharkhand", ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar"]],
  "KA": ["Karnataka", ["Bengaluru", "Mysuru", "Mangaluru", "Hubli", "Belgaum"]],
  "KL": ["Kerala", ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kannur"]],
  "MP": ["Madhya Pradesh", ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain"]],
  "MH": ["Maharashtra", ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"]],
  "MN": ["Manipur", ["Imphal", "Churachandpur", "Thoubal", "Bishnupur", "Kakching"]],
  "ML": ["Meghalaya", ["Shillong", "Tura", "Nongstoin", "Jowai", "Baghmara"]],
  "MZ": ["Mizoram", ["Aizawl", "Lunglei", "Saiha", "Champhai", "Kolasib"]],
  "NL": ["Nagaland", ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha"]],
  "OR": ["Odisha", ["Bhubaneswar", "Cuttack", "Rourkela", "Puri", "Sambalpur"]],
  "PB": ["Punjab", ["Amritsar", "Ludhiana", "Jalandhar", "Patiala", "Bathinda"]],
  "RJ": ["Rajasthan", ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer"]],
  "SK": ["Sikkim", ["Gangtok", "Namchi", "Gyalshing", "Mangan", "Rangpo"]],
  "TN": ["Tamil Nadu", ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"]],
  "TG": ["Telangana", ["Hyderabad", "Warangal", "Nizamabad", "Khammam", "Karimnagar"]],
  "TR": ["Tripura", ["Agartala", "Udaipur", "Kailasahar", "Dharmanagar", "Belonia"]],
  "UP": ["Uttar Pradesh", ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi"]],
  "UT": ["Uttarakhand", ["Dehradun", "Haridwar", "Roorkee", "Haldwani", "Nainital"]],
  "WB": ["West Bengal", ["Kolkata", "Howrah", "Durgapur", "Siliguri", "Asansol"]],
  "AN": ["Andaman and Nicobar Islands", ["Port-Blair", "Havelock-Island", "Neil-Island", "Baratang", "Little Andaman"]],
  "CH": ["Chandigarh", ["Chandigarh"]],
  "DN": ["Dadra and Nagar Haveli", ["Dadra-and-Nagar-Haveli"]],
  "DD": ["Daman and Diu", ["Daman", "Diu"]],
  "LD": ["Lakshadweep", ["Lakshadweep"]],
  "DL": ["Delhi", ["Delhi"]],
  "PY": ["Puducherry", ["Puducherry"]],
  "LA": ["Ladakh", ["Leh", "Kargil"]],
  "JK": ["Jammu and Kashmir", ["Srinagar", "Jammu"]]
};
